// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using NZWalks.API.Data;

#nullable disable

namespace NZWalks.API.Migrations
{
    [DbContext(typeof(NZWalksDbContext))]
    partial class NZWalksDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.3")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("NZWalks.API.Models.Domain.Difficulty", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("Difficulties");

                    b.HasData(
                        new
                        {
                            Id = new Guid("053c1043-6fb4-41b9-9d3c-26a498a1413d"),
                            Name = "Easy"
                        },
                        new
                        {
                            Id = new Guid("b88cfd61-9477-4e1d-b84b-dadaa0184bdf"),
                            Name = "Medium"
                        },
                        new
                        {
                            Id = new Guid("9a3de88c-1a60-4c91-9461-af43cacd1005"),
                            Name = "Hard"
                        });
                });

            modelBuilder.Entity("NZWalks.API.Models.Domain.Image", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("FileDescription")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("FileExtension")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("FileName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("FilePath")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<long>("FileSizeInBytes")
                        .HasColumnType("bigint");

                    b.HasKey("Id");

                    b.ToTable("Images");
                });

            modelBuilder.Entity("NZWalks.API.Models.Domain.Region", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Code")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("RegionImageUrl")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("Regions");

                    b.HasData(
                        new
                        {
                            Id = new Guid("f3b3b3b3-6fb4-41b9-9d3c-26a498a1413d"),
                            Code = "",
                            Name = "Northland"
                        },
                        new
                        {
                            Id = new Guid("b88cfd61-9477-4e1d-b84b-dadaa0184bdf"),
                            Code = "",
                            Name = "Auckland",
                            RegionImageUrl = "https://images.pexels.com/photos/4350631/pexels-photo-4350631.jpg"
                        },
                        new
                        {
                            Id = new Guid("9a3de88c-1a60-4c91-9461-af43cacd1005"),
                            Code = "",
                            Name = "Waikato",
                            RegionImageUrl = "https://images.pexels.com/photos/4350631/pexels-photo-4350631.jpg"
                        },
                        new
                        {
                            Id = new Guid("5db28a12-9b19-4046-b6ad-01dc5a63b7de"),
                            Code = "",
                            Name = "Bay of Plenty",
                            RegionImageUrl = "https://images.pexels.com/photos/13918194/pexels-photo-13918194.jpg"
                        },
                        new
                        {
                            Id = new Guid("5025788f-9ab6-4778-bdc6-46623d1e8de5"),
                            Code = "",
                            Name = "Gisborne"
                        },
                        new
                        {
                            Id = new Guid("4bf96fb5-4419-404b-96b2-3b894d0ba2f5"),
                            Code = "",
                            Name = "Hawke's Bay",
                            RegionImageUrl = "https://images.pexels.com/photos/4350631/pexels-photo-4350631.jpg"
                        },
                        new
                        {
                            Id = new Guid("fed42b58-fd6a-4dad-a57f-4cb452ba4a8f"),
                            Code = "",
                            Name = "Taranaki",
                            RegionImageUrl = "https://images.pexels.com/photos/13918194/pexels-photo-13918194.jpg"
                        },
                        new
                        {
                            Id = new Guid("9c11f8b5-252f-4808-a2b3-726d1d26f311"),
                            Code = "",
                            Name = "Manawatu-Wanganui"
                        },
                        new
                        {
                            Id = new Guid("b92ebf56-42fc-412b-9732-247a1921165c"),
                            Code = "",
                            Name = "Wellington",
                            RegionImageUrl = "https://images.pexels.com/photos/4350631/pexels-photo-4350631.jpg"
                        },
                        new
                        {
                            Id = new Guid("1b8d43d6-21ca-40b2-9c20-85a4e8750475"),
                            Code = "",
                            Name = "Tasman",
                            RegionImageUrl = "https://images.pexels.com/photos/13918194/pexels-photo-13918194.jpg"
                        },
                        new
                        {
                            Id = new Guid("b39553be-de94-4d3b-a231-0ede8cf20a6e"),
                            Code = "",
                            Name = "Nelson"
                        });
                });

            modelBuilder.Entity("NZWalks.API.Models.Domain.Walk", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<Guid>("DifficultyId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<double>("LengthInKm")
                        .HasColumnType("float");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<Guid>("RegionId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("WalkImageUrl")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.HasIndex("DifficultyId");

                    b.HasIndex("RegionId");

                    b.ToTable("Walks");
                });

            modelBuilder.Entity("NZWalks.API.Models.Domain.Walk", b =>
                {
                    b.HasOne("NZWalks.API.Models.Domain.Difficulty", "Difficulty")
                        .WithMany()
                        .HasForeignKey("DifficultyId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("NZWalks.API.Models.Domain.Region", "Region")
                        .WithMany()
                        .HasForeignKey("RegionId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Difficulty");

                    b.Navigation("Region");
                });
#pragma warning restore 612, 618
        }
    }
}
